# Site settings
title: Meuse
email: snuxlab@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  서울대학교 융합과학기술대학원 사용자 경험 연구실
baseurl: "/" 
url: "https://snuxlab.github.io/website/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"
